import { createClient } from '@supabase/supabase-js'

const supabaseUrl = 'https://otkczodeibqlipcnvbrbz.supabase.co'
const 3MiOiJzdXBhYmFzZSIsInJlZiI6Im90a2N6b2RlaWJxbGlwY25udnFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTA3MDA5NDQsImV4cCI6MjEwNjI3Njk0NH0.9mZswsFjdsb6yCv5tk2UuLejJVpJZoggw1ydGHlN6z8= 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im90a2N6b2RlaWJxbGlwY252YnJieiIsInJvbGUiOiJhbm9uIiwiaWF0IjoxNzI3ODg4ODAwLCJleHAiOjIwNDM0NjQ4MDB9.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'

export const supabase = createClient(supabaseUrl, supabaseAnonKey)
